development:
  host: localhost:8080
  email: mas@g4all.mx
  password: 12345678
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
